// packages/web-portal/vector-web/src/lib/turnstile.ts

interface TurnstileVerifyResponse {
  success: boolean;
  error_codes?: string[];
  challenge_ts?: string;
  hostname?: string;
}

/**
 * Verifies a Cloudflare Turnstile token against the Cloudflare API.
 * @param token - The token generated by the client-side Turnstile widget.
 * @returns A boolean indicating whether the verification was successful.
 */
export async function verifyTurnstileToken(token: string | null | undefined): Promise<boolean> {
  const secretKey = process.env.TURNSTILE_SECRET_KEY;

  if (!secretKey) {
    console.error("TURNSTILE_SECRET_KEY is missing from environment variables.");
    return false;
  }

  if (!token) {
    console.warn("Turnstile token was missing from the request.");
    return false;
  }

  try {
    const formData = new FormData();
    formData.append("secret", secretKey);
    formData.append("response", token);

    const response = await fetch("https://challenges.cloudflare.com/turnstile/v0/siteverify", {
      method: "POST",
      body: formData,
    });

    const data: TurnstileVerifyResponse = await response.json();

    if (!data.success) {
      console.error("Turnstile verification failed. Error codes:", data.error_codes);
      return false;
    }

    return true;
  } catch (error) {
    console.error("Network or parsing error during Turnstile verification:", error);
    return false;
  }
}