import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy — Vector',
  description: 'Learn how Vector collects, uses, and protects your personal data.',
};

export default function PrivacyPolicyPage() {
  return (
    <article className="max-w-4xl mx-auto px-6 py-16">
      {/* Header */}
      <div className="mb-12">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-[#06B4C9]/20 bg-[#06B4C9]/5 mb-5">
          <span className="text-xs font-medium text-[#06B4C9]">Legal</span>
        </div>
        <h1 className="text-3xl sm:text-4xl font-bold text-gray-900 mb-3">Privacy Policy</h1>
        <p className="text-gray-400 text-sm">Last updated: March 2, 2026</p>
      </div>

      <div className="prose prose-gray max-w-none space-y-10 [&_h2]:text-xl [&_h2]:font-bold [&_h2]:text-gray-900 [&_h2]:mb-4 [&_p]:text-gray-600 [&_p]:leading-relaxed [&_li]:text-gray-600 [&_li]:leading-relaxed">
        {/* 1. Introduction */}
        <section>
          <h2>1. Introduction</h2>
          <p>
            Vector (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;) operates an AI-powered credentialing and career analytics platform that combines institutional credential verification with AI-powered skill analytics. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our platform.
          </p>
          <p>
            By creating an account or using Vector, you agree to the collection and use of information in accordance with this policy.
          </p>
        </section>

        {/* 2. Information We Collect */}
        <section>
          <h2>2. Information We Collect</h2>

          <h3 className="text-base font-semibold text-gray-800 mt-6 mb-2">2.1 Account Information</h3>
          <p>When you register, we collect:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Full name and email address</li>
            <li>Student ID (for student accounts)</li>
            <li>Role designation (Student, Registrar, or Super Admin)</li>
            <li>Profile information including university, major, graduation year, bio, and phone number</li>
            <li>Portfolio links (GitHub, LinkedIn, personal portfolio)</li>
          </ul>



          <h3 className="text-base font-semibold text-gray-800 mt-6 mb-2">2.3 Credential &amp; Academic Data</h3>
          <ul className="list-disc pl-6 space-y-1">
            <li>Verified credentials issued by registrars (skill name, issuer, certificate number)</li>
            <li>Self-reported skills with proficiency levels and evidence links</li>
            <li>Resume text submitted for AI skill extraction</li>
            <li>Course enrollment records and completion status</li>
          </ul>

          <h3 className="text-base font-semibold text-gray-800 mt-6 mb-2">2.4 AI &amp; Analytics Data</h3>
          <ul className="list-disc pl-6 space-y-1">
            <li>Skill health scores and market relevance metrics derived from job market analysis</li>
            <li>Career recommendations generated by our AI engine</li>
            <li>Skill decay predictions based on aggregated market trends</li>
          </ul>

          <h3 className="text-base font-semibold text-gray-800 mt-6 mb-2">2.5 Technical &amp; Usage Data</h3>
          <ul className="list-disc pl-6 space-y-1">
            <li>IP address, user agent, and browser information</li>
            <li>System traffic logs (HTTP method, path, status code, response time)</li>
            <li>Rate limiting data to prevent abuse</li>
          </ul>
        </section>

        {/* 3. How We Use Your Information */}
        <section>
          <h2>3. How We Use Your Information</h2>
          <p>We use the information we collect to:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Create, manage, and authenticate your account via Supabase authentication</li>
            <li>Issue, verify, and manage institution-backed micro-credentials</li>
            <li>Provide AI-powered career analytics, including skill decay detection and course recommendations</li>
            <li>Generate Credential Verification Reports (CVR) for sharing with employers</li>
            <li>Send notifications about credential updates, verification status, and platform alerts</li>
            <li>Enforce role-based access control (RBAC) across Student, Registrar, and Admin portals</li>
            <li>Maintain audit logs for administrative accountability and compliance</li>
            <li>Monitor system performance and prevent abuse through rate limiting</li>
          </ul>
        </section>

        {/* 4. Data Protection */}
        <section>
          <h2>4. Data Protection &amp; Security</h2>
          <p>We implement multiple layers of security to protect your data:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li><strong>Encryption at Rest:</strong> Sensitive fields such as private instructor notes are encrypted using AES-256 before storage</li>
            <li><strong>Authentication:</strong> Account sessions are managed through Supabase with secure cookie-based session management and server-side validation</li>
            <li><strong>Input Validation:</strong> All API endpoints validate input using Zod schemas before processing</li>
            <li><strong>Rate Limiting:</strong> Automated protection against brute-force and denial-of-service attacks</li>
            <li><strong>Audit Logging:</strong> Immutable logs track every administrative action and verification event</li>
            <li><strong>Email Verification:</strong> All accounts require email verification with time-limited codes before activation</li>
          </ul>
          <p>For more technical details, see our <a href="/security" className="text-[#06B4C9] hover:underline">Security page</a>.</p>
        </section>

        {/* 5. Verification Immutability */}
        <section>
          <h2>5. Verification Immutability</h2>
          <p>
            Credentials issued by Registrars are stored securely to maintain their integrity. Once a credential is issued:
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li>The official record is permanently logged in our audit system</li>
            <li>Credentials are tied to verified student identities, preventing fraud</li>
            <li>Only verified Registrars (institutions) can issue credentials</li>
          </ul>
          <p>
            Profile information, self-reported skills, and private notes can be modified or deleted upon request, subject to audit log retention requirements.
          </p>
        </section>

        {/* 6. Third-Party Services */}
        <section>
          <h2>6. Third-Party Services</h2>
          <p>Vector integrates with the following third-party services:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li><strong>Supabase:</strong> Authentication, database hosting (PostgreSQL), and real-time services</li>

            <li><strong>Google Gemini AI:</strong> Natural language processing for skill extraction from resumes (text is processed in real-time and not stored by the AI provider for training)</li>
            <li><strong>Adzuna &amp; JSearch APIs:</strong> Anonymized job market data aggregation for skill health analytics</li>
            <li><strong>Cloudflare Turnstile:</strong> Bot detection and CAPTCHA verification on authentication forms</li>
          </ul>
          <p>
            Each third-party service operates under its own privacy policy. We only share the minimum data necessary for each service to function.
          </p>
        </section>

        {/* 7. Data Retention */}
        <section>
          <h2>7. Data Retention</h2>
          <ul className="list-disc pl-6 space-y-1">
            <li><strong>Account Data:</strong> Retained for as long as your account is active. Upon account deletion, off-chain data is removed within 30 days</li>
            <li><strong>Audit Logs:</strong> Retained indefinitely for compliance and accountability purposes</li>

            <li><strong>System Logs:</strong> Retained for 90 days for performance monitoring and security analysis</li>
            <li><strong>Rate Limiting Data:</strong> Automatically expires and is cleared periodically</li>
          </ul>
        </section>

        {/* 8. Your Rights */}
        <section>
          <h2>8. Your Rights</h2>
          <p>Depending on your jurisdiction, you may have the right to:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li><strong>Access:</strong> Request a copy of the personal data we hold about you</li>
            <li><strong>Rectification:</strong> Update or correct inaccurate information through your profile settings</li>
            <li><strong>Deletion:</strong> Request deletion of your personal data (audit logs of verified credentials may be retained for compliance)</li>
            <li><strong>Portability:</strong> Export your credential data via CVR reports</li>
            <li><strong>Objection:</strong> Opt out of AI-powered analytics processing</li>
          </ul>
          <p>
            To exercise any of these rights, contact us at <a href="mailto:privacy@vector.edu" className="text-[#06B4C9] hover:underline">privacy@vector.edu</a>.
          </p>
        </section>

        {/* 9. Children's Privacy */}
        <section>
          <h2>9. Children&apos;s Privacy</h2>
          <p>
            Vector is designed for university students and institutional staff. We do not knowingly collect information from individuals under the age of 16. If you believe we have collected data from a minor, please contact us immediately.
          </p>
        </section>

        {/* 10. Changes */}
        <section>
          <h2>10. Changes to This Policy</h2>
          <p>
            We may update this Privacy Policy from time to time. Material changes will be communicated through platform notifications and a prominent notice on our website. Continued use of Vector after changes constitutes acceptance of the revised policy.
          </p>
        </section>

        {/* 11. Contact */}
        <section>
          <h2>11. Contact Us</h2>
          <p>
            If you have questions about this Privacy Policy or our data practices, contact us at:
          </p>
          <ul className="list-none pl-0 space-y-1">
            <li><strong>Email:</strong> <a href="mailto:privacy@vector.edu" className="text-[#06B4C9] hover:underline">privacy@vector.edu</a></li>
            <li><strong>Platform:</strong> <a href="https://vector.app" className="text-[#06B4C9] hover:underline">vector.app</a></li>
          </ul>
        </section>
      </div>
    </article>
  );
}
